from __future__ import annotations

from unity_integration.contracts import UnityCapabilityDefinition, UnityEnvironmentConfig


class UnityCapabilityCatalog:
    _DEFINITIONS: dict[str, UnityCapabilityDefinition] = {
        "editor.launch": UnityCapabilityDefinition(
            capability="editor.launch",
            category="editor",
            description="Launch the Unity project with Unity CLI Loop or attach through the GUI profile.",
            supported_backends=("cli_loop", "gui"),
            preferred_backend="cli_loop",
            gui_macro="attach_editor",
            cli_loop_command="launch",
        ),
        "editor.compile": UnityCapabilityDefinition(
            capability="editor.compile",
            category="editor",
            description="Compile the active Unity project and capture the result as artifacts.",
            supported_backends=("cli_loop",),
            preferred_backend="cli_loop",
            cli_loop_command="compile",
        ),
        "editor.logs.read": UnityCapabilityDefinition(
            capability="editor.logs.read",
            category="editor",
            description="Read Unity console logs through Unity CLI Loop with artifact-first output capture.",
            supported_backends=("cli_loop",),
            preferred_backend="cli_loop",
            cli_loop_command="get-logs",
        ),
        "editor.tests.editmode": UnityCapabilityDefinition(
            capability="editor.tests.editmode",
            category="testing",
            description="Run Unity EditMode tests through Unity CLI Loop.",
            supported_backends=("cli_loop",),
            preferred_backend="cli_loop",
            cli_loop_command="run-tests",
            manual_validation_required=True,
        ),
        "editor.tests.playmode": UnityCapabilityDefinition(
            capability="editor.tests.playmode",
            category="testing",
            description="Run Unity PlayMode tests through Unity CLI Loop.",
            supported_backends=("cli_loop",),
            preferred_backend="cli_loop",
            cli_loop_command="run-tests",
            manual_validation_required=True,
        ),
        "editor.playmode.control": UnityCapabilityDefinition(
            capability="editor.playmode.control",
            category="editor",
            description="Control Play Mode through CLI Loop, MCP, or GUI fallback.",
            supported_backends=("cli_loop", "mcp", "gui"),
            preferred_backend="cli_loop",
            mcp_tool_name="manage_editor",
            gui_fallback_macro="play_mode",
            cli_loop_command="control-play-mode",
            fallbackable=True,
        ),
        "editor.window.focus": UnityCapabilityDefinition(
            capability="editor.window.focus",
            category="editor",
            description="Bring the Unity editor window to the foreground.",
            supported_backends=("cli_loop", "gui"),
            preferred_backend="cli_loop",
            gui_macro="attach_editor",
            cli_loop_command="focus-window",
            manual_validation_required=True,
        ),
        "editor.screenshot.capture": UnityCapabilityDefinition(
            capability="editor.screenshot.capture",
            category="editor",
            description="Capture a named Unity editor window as a screenshot artifact.",
            supported_backends=("cli_loop", "gui"),
            preferred_backend="cli_loop",
            gui_macro="capture_view",
            cli_loop_command="screenshot",
            manual_validation_required=True,
        ),
        "scene.hierarchy.export": UnityCapabilityDefinition(
            capability="scene.hierarchy.export",
            category="scene",
            description="Export hierarchy data for the active scene.",
            supported_backends=("cli_loop", "mcp"),
            preferred_backend="cli_loop",
            mcp_tool_name="manage_scene",
            mcp_default_params={"action": "get_hierarchy"},
            cli_loop_command="get-hierarchy",
        ),
        "scene.inspect": UnityCapabilityDefinition(
            capability="scene.inspect",
            category="scene",
            description="Inspect active scene structure and metadata using hierarchy export primitives.",
            supported_backends=("cli_loop", "mcp"),
            preferred_backend="cli_loop",
            mcp_tool_name="manage_scene",
            mcp_default_params={"action": "get_hierarchy"},
            cli_loop_command="get-hierarchy",
        ),
        "scene.open": UnityCapabilityDefinition(
            capability="scene.open",
            category="scene",
            description="Open a Unity scene through MCP scene management.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_scene",
            mcp_default_params={"action": "load"},
            gui_fallback_macro="open_scene",
            fallbackable=True,
        ),
        "scene.save": UnityCapabilityDefinition(
            capability="scene.save",
            category="scene",
            description="Save the current Unity scene through the GUI profile.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="save_scene",
            manual_validation_required=True,
        ),
        "gameobject.find": UnityCapabilityDefinition(
            capability="gameobject.find",
            category="gameobject",
            description="Find GameObjects using Unity Skills style capability routing.",
            supported_backends=("cli_loop", "mcp"),
            preferred_backend="mcp",
            mcp_tool_name="find_gameobjects",
            cli_loop_command="find-game-objects",
        ),
        "gameobject.create": UnityCapabilityDefinition(
            capability="gameobject.create",
            category="gameobject",
            description="Create a GameObject through MCP-backed object management.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_gameobject",
            gui_fallback_macro="create_gameobject",
            fallbackable=True,
        ),
        "gameobject.modify": UnityCapabilityDefinition(
            capability="gameobject.modify",
            category="gameobject",
            description="Modify an existing GameObject through MCP-backed object management.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_gameobject",
        ),
        "gameobject.delete": UnityCapabilityDefinition(
            capability="gameobject.delete",
            category="gameobject",
            description="Delete a GameObject through MCP-backed object management.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_gameobject",
            gui_fallback_macro="delete_selection",
            fallbackable=True,
            manual_validation_required=True,
        ),
        "component.add": UnityCapabilityDefinition(
            capability="component.add",
            category="component",
            description="Add a component to a GameObject.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_components",
            gui_fallback_macro="add_component",
            fallbackable=True,
        ),
        "script.create_or_update": UnityCapabilityDefinition(
            capability="script.create_or_update",
            category="script",
            description="Create or update a Unity C# script file through the MCP lane.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="create_script",
            manual_validation_required=True,
        ),
        "prefab.inspect": UnityCapabilityDefinition(
            capability="prefab.inspect",
            category="prefab",
            description="Inspect prefabs through MCP-backed prefab management.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_prefabs",
            manual_validation_required=True,
        ),
        "asset.search": UnityCapabilityDefinition(
            capability="asset.search",
            category="asset",
            description="Search or inspect assets through MCP-backed asset management.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_asset",
        ),
        "editor.menu.execute": UnityCapabilityDefinition(
            capability="editor.menu.execute",
            category="editor",
            description="Execute a Unity menu item through CLI Loop or MCP.",
            supported_backends=("cli_loop", "mcp"),
            preferred_backend="cli_loop",
            mcp_tool_name="execute_menu_item",
            cli_loop_command="execute-menu-item",
            manual_validation_required=True,
        ),
        "animation.manage": UnityCapabilityDefinition(
            capability="animation.manage",
            category="animation",
            description="Run supported animation operations exposed by manage_animation.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_animation",
        ),
        "animator.graph.manage": UnityCapabilityDefinition(
            capability="animator.graph.manage",
            category="animation",
            description="Manage Animator controller graphs through manage_animation.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_animation",
            manual_validation_required=True,
        ),
        "asset.manage": UnityCapabilityDefinition(
            capability="asset.manage",
            category="asset",
            description="Run supported manage_asset operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_asset",
        ),
        "build.manage": UnityCapabilityDefinition(
            capability="build.manage",
            category="build",
            description="Run supported manage_build operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_build",
            manual_validation_required=True,
        ),
        "camera.manage": UnityCapabilityDefinition(
            capability="camera.manage",
            category="camera",
            description="Run supported manage_camera operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_camera",
        ),
        "component.manage": UnityCapabilityDefinition(
            capability="component.manage",
            category="component",
            description="Run supported manage_components operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_components",
        ),
        "editor.attach": UnityCapabilityDefinition(
            capability="editor.attach",
            category="editor",
            description="Attach to or launch the current Unity editor window.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="attach_editor",
        ),
        "editor.console.snapshot": UnityCapabilityDefinition(
            capability="editor.console.snapshot",
            category="editor",
            description="Copy and persist the visible Unity console text.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="snapshot_console",
            manual_validation_required=True,
        ),
        "editor.control_tree.dump": UnityCapabilityDefinition(
            capability="editor.control_tree.dump",
            category="editor",
            description="Dump UI Automation control trees for the active Unity editor window.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="dump_control_tree",
        ),
        "editor.layout.assert": UnityCapabilityDefinition(
            capability="editor.layout.assert",
            category="editor",
            description="Assert the pinned Unity layout and modal state before automation.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="assert_layout_ready",
        ),
        "editor.layout.normalize": UnityCapabilityDefinition(
            capability="editor.layout.normalize",
            category="editor",
            description="Normalize the Unity editor layout through MCP-backed menu execution.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="batch_execute",
            manual_validation_required=True,
        ),
        "editor.manage": UnityCapabilityDefinition(
            capability="editor.manage",
            category="editor",
            description="Run supported manage_editor operations.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_editor",
            fallbackable=True,
        ),
        "editor.pause": UnityCapabilityDefinition(
            capability="editor.pause",
            category="editor",
            description="Pause play mode.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_editor",
            mcp_default_params={"action": "pause"},
            gui_fallback_macro="pause_mode",
            fallbackable=True,
        ),
        "editor.play": UnityCapabilityDefinition(
            capability="editor.play",
            category="editor",
            description="Enter play mode.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_editor",
            mcp_default_params={"action": "play"},
            gui_fallback_macro="play_mode",
            fallbackable=True,
        ),
        "editor.stop": UnityCapabilityDefinition(
            capability="editor.stop",
            category="editor",
            description="Stop play mode.",
            supported_backends=("mcp", "gui"),
            preferred_backend="mcp",
            mcp_tool_name="manage_editor",
            mcp_default_params={"action": "stop"},
            gui_fallback_macro="stop_mode",
            fallbackable=True,
        ),
        "editor.surface.focus": UnityCapabilityDefinition(
            capability="editor.surface.focus",
            category="editor",
            description="Focus a pinned Unity surface in the current layout.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="focus_hierarchy",
        ),
        "editor.view.capture": UnityCapabilityDefinition(
            capability="editor.view.capture",
            category="editor",
            description="Capture a pinned Unity surface by GUI coordinates.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="capture_view",
            manual_validation_required=True,
        ),
        "editor.window.open": UnityCapabilityDefinition(
            capability="editor.window.open",
            category="editor",
            description="Open a Unity editor window through the Window menu.",
            supported_backends=("gui",),
            preferred_backend="gui",
            gui_macro="open_window",
            manual_validation_required=True,
        ),
        "gameobject.manage": UnityCapabilityDefinition(
            capability="gameobject.manage",
            category="gameobject",
            description="Run supported manage_gameobject operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_gameobject",
        ),
        "graphics.manage": UnityCapabilityDefinition(
            capability="graphics.manage",
            category="graphics",
            description="Run supported manage_graphics operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_graphics",
            manual_validation_required=True,
        ),
        "material.manage": UnityCapabilityDefinition(
            capability="material.manage",
            category="material",
            description="Run supported manage_material operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_material",
        ),
        "package.manage": UnityCapabilityDefinition(
            capability="package.manage",
            category="package",
            description="Run supported manage_packages operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_packages",
            manual_validation_required=True,
        ),
        "prefab.manage": UnityCapabilityDefinition(
            capability="prefab.manage",
            category="prefab",
            description="Run supported manage_prefabs operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_prefabs",
        ),
        "scene.manage": UnityCapabilityDefinition(
            capability="scene.manage",
            category="scene",
            description="Run supported manage_scene operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_scene",
        ),
        "shader.graph.manage": UnityCapabilityDefinition(
            capability="shader.graph.manage",
            category="graphics",
            description="Planned Shader Graph mutations; backend graph operations are not yet available.",
            supported_backends=tuple(),
            preferred_backend="mcp",
        ),
        "shader.manage": UnityCapabilityDefinition(
            capability="shader.manage",
            category="graphics",
            description="Run supported manage_shader operations for shader assets.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_shader",
            manual_validation_required=True,
        ),
        "texture.manage": UnityCapabilityDefinition(
            capability="texture.manage",
            category="graphics",
            description="Run supported manage_texture operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_texture",
            manual_validation_required=True,
        ),
        "tests.run": UnityCapabilityDefinition(
            capability="tests.run",
            category="tests",
            description="Start a Unity test run.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="run_tests",
            manual_validation_required=True,
        ),
        "tests.status": UnityCapabilityDefinition(
            capability="tests.status",
            category="tests",
            description="Poll a running Unity test job.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="get_test_job",
            manual_validation_required=True,
        ),
        "timeline.manage": UnityCapabilityDefinition(
            capability="timeline.manage",
            category="timeline",
            description="Planned Timeline mutations; no active backend surface is wired yet.",
            supported_backends=tuple(),
            preferred_backend="mcp",
        ),
        "ui.manage": UnityCapabilityDefinition(
            capability="ui.manage",
            category="ui",
            description="Run supported manage_ui operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_ui",
            manual_validation_required=True,
        ),
        "vfx.graph.manage": UnityCapabilityDefinition(
            capability="vfx.graph.manage",
            category="graphics",
            description="Planned VFX Graph mutations; backend graph operations are not yet available.",
            supported_backends=tuple(),
            preferred_backend="mcp",
        ),
        "vfx.manage": UnityCapabilityDefinition(
            capability="vfx.manage",
            category="graphics",
            description="Run supported manage_vfx operations.",
            supported_backends=("mcp",),
            preferred_backend="mcp",
            mcp_tool_name="manage_vfx",
            manual_validation_required=True,
        ),
    }

    @classmethod
    def all(cls) -> list[UnityCapabilityDefinition]:
        return [cls._DEFINITIONS[name] for name in cls.names()]

    @classmethod
    def names(cls) -> list[str]:
        return sorted(cls._DEFINITIONS)

    @classmethod
    def get(cls, capability: str) -> UnityCapabilityDefinition:
        if capability not in cls._DEFINITIONS:
            known = ", ".join(cls.names())
            raise ValueError(f"Unknown Unity capability '{capability}'. Known capabilities: {known}")
        return cls._DEFINITIONS[capability]

    @classmethod
    def build_matrix(cls, environment: UnityEnvironmentConfig) -> list[dict[str, object]]:
        rows: list[dict[str, object]] = []
        backend_availability = {
            "cli_loop": bool(environment.cli_loop_command) and environment.cli_loop_installed,
            "mcp": bool(environment.unity_mcp_command) and environment.unity_mcp_available,
            "gui": True,
        }
        for item in cls.all():
            available_backends = [backend for backend in item.supported_backends if backend_availability.get(backend, False)]
            rows.append(
                {
                    "capability": item.capability,
                    "category": item.category,
                    "description": item.description,
                    "preferred_backend": item.preferred_backend,
                    "supported_backends": list(item.supported_backends),
                    "available_backends": available_backends,
                    "manual_validation_required": item.manual_validation_required,
                    "mcp_tool_name": item.mcp_tool_name,
                    "cli_loop_command": item.cli_loop_command,
                    "gui_macro": item.gui_macro or item.gui_fallback_macro,
                }
            )
        return rows
