from __future__ import annotations

import hashlib
import json
from pathlib import Path

from orchestrator.catalog import load_platform_catalog


def generate_surfaces(repo_root: Path) -> dict[Path, str]:
    ai_root = repo_root / "ai-dev-system"
    catalog = load_platform_catalog(ai_root)
    surfaces: dict[Path, str] = {}

    catalog_hash = hashlib.sha256(catalog.source_path.read_bytes()).hexdigest()

    surfaces[repo_root / ".codex" / "AGENTS.md"] = _render_codex_agents(catalog, repo_root)
    surfaces[repo_root / ".codex" / "config.toml"] = _render_codex_config()

    harness_agents = [agent for agent in catalog.agents.values() if agent.codex]
    for agent in harness_agents:
        file_name = str(agent.codex.get("file_name") or agent.id)
        surfaces[repo_root / ".codex" / "agents" / f"{file_name}.toml"] = _render_codex_agent(agent)

    for skill in catalog.skills.values():
        skill_root = repo_root / ".agents" / "skills" / skill.id
        surfaces[skill_root / "SKILL.md"] = _render_skill_markdown(skill)
        surfaces[skill_root / "agents" / "openai.yaml"] = _render_skill_openai(skill)

    antigravity_files: list[str] = []
    for rule_pack in catalog.rule_packs.values():
        path = repo_root / ".agent" / "rules" / f"{rule_pack.id}.md"
        surfaces[path] = _render_antigravity_rule(catalog, rule_pack)
        antigravity_files.append(_relative_to_repo(path, repo_root))

    for workflow in catalog.workflows.values():
        path = repo_root / ".agent" / "workflows" / f"{workflow.id}.md"
        surfaces[path] = _render_antigravity_workflow(workflow)
        antigravity_files.append(_relative_to_repo(path, repo_root))

    for agent in harness_agents:
        file_name = str((agent.antigravity or {}).get("file_name") or f"{agent.id}.md")
        path = repo_root / ".agent" / "skills" / file_name
        surfaces[path] = _render_antigravity_agent(agent)
        antigravity_files.append(_relative_to_repo(path, repo_root))

    state_path = repo_root / ".agent" / "agent-platform-install-state.json"
    antigravity_files.append(_relative_to_repo(state_path, repo_root))
    surfaces[state_path] = json.dumps(
        {
            "version": 1,
            "catalog": _relative_to_repo(catalog.source_path, repo_root),
            "catalog_sha256": catalog_hash,
            "files": sorted(antigravity_files)
        },
        indent=2
    ) + "\n"

    return surfaces


def _render_codex_agents(catalog, repo_root: Path) -> str:
    workflow = catalog.require_workflow("unity-autonomous-loop")
    lines = [
        "# Generated Codex Surface",
        "",
        "Do not edit this file by hand.",
        "Run `python ai-dev-system/scripts/sync-agent-surfaces.py` after changing the canonical catalog.",
        "",
        "## Source Of Truth",
        "",
        f"- Canonical catalog: `{_relative_to_repo(catalog.source_path, repo_root)}`",
        "- Governance: `AGENTS.md`, `ai-dev-system/AGENTS.md`",
        "- Policy packs: `ai-dev-system/context/policies/agent-platform-governance.md`, `ai-dev-system/context/policies/verification-gates.md`",
        "",
        "## Workflow",
        "",
        f"- Default workflow: `{workflow.id}`",
        f"- Phases: {', '.join(workflow.phases)}",
        f"- Side states: {', '.join(workflow.side_states)}",
        f"- Supported goals: {', '.join(workflow.supported_goals)}",
        "",
        "## Harness Agents",
        ""
    ]
    for agent in catalog.agents.values():
        if not agent.codex:
            continue
        file_name = str(agent.codex.get("file_name") or agent.id)
        lines.append(f"- `{file_name}`: {agent.summary}")

    lines.extend(["", "## Shared Skills", ""])
    for skill in catalog.skills.values():
        lines.append(f"- `{skill.id}`: {skill.summary}")

    lines.extend(
        [
            "",
            "## Verification Expectations",
            "",
            "- Treat the canonical catalog as the harness source of truth.",
            "- Regenerate `.codex/`, `.agents/skills/`, and `.agent/` when the catalog changes.",
            "- Do not close work without tests or drift-check evidence.",
            ""
        ]
    )
    return "\n".join(lines)


def _render_codex_config() -> str:
    return (
        "#:schema https://developers.openai.com/codex/config-schema.json\n"
        "\n"
        "# Generated from ai-dev-system/control-plane/catalog/platform.json\n"
        "approval_policy = \"on-request\"\n"
        "sandbox_mode = \"workspace-write\"\n"
        "persistent_instructions = \"Follow AGENTS.md and .codex/AGENTS.md. Treat ai-dev-system/control-plane/catalog/platform.json as the canonical agent-platform source of truth.\"\n"
    )


def _render_codex_agent(agent) -> str:
    model = str(agent.codex.get("model") or "gpt-5.4")
    reasoning_effort = str(agent.codex.get("reasoning_effort") or "medium")
    sandbox_mode = str(agent.codex.get("sandbox_mode") or "read-only")
    responsibilities = "\n".join(f"- {item}" for item in agent.responsibilities)
    outputs = "\n".join(f"- {item}" for item in agent.outputs)
    developer_instructions = (
        f"Role: {agent.name}\n"
        f"Summary: {agent.summary}\n"
        f"Prompt source: {agent.prompt}\n"
        "Responsibilities:\n"
        f"{responsibilities}\n"
        "Outputs:\n"
        f"{outputs}\n"
        "Keep recommendations aligned with the canonical catalog and exported harness surfaces."
    )
    return (
        f"model = \"{model}\"\n"
        f"model_reasoning_effort = \"{reasoning_effort}\"\n"
        f"sandbox_mode = \"{sandbox_mode}\"\n"
        "\n"
        "developer_instructions = \"\"\"\n"
        f"{developer_instructions}\n"
        "\"\"\"\n"
    )


def _render_skill_markdown(skill) -> str:
    lines = [
        "---",
        f"name: {skill.id}",
        f"description: {skill.summary}",
        "origin: app_tro_ly canonical catalog",
        "---",
        "",
        f"# {skill.name}",
        "",
        skill.summary,
        "",
        "## Triggers",
        ""
    ]
    lines.extend(f"- {item}" for item in skill.triggers)
    lines.extend(["", "## Checklist", ""])
    lines.extend(f"- {item}" for item in skill.checklist)
    lines.extend(["", "## Outputs", ""])
    lines.extend(f"- {item}" for item in skill.outputs)
    lines.append("")
    return "\n".join(lines)


def _render_skill_openai(skill) -> str:
    openai = skill.openai
    allow_implicit = "true" if openai.get("allow_implicit_invocation") else "false"
    return (
        "interface:\n"
        f"  display_name: \"{openai.get('display_name', skill.name)}\"\n"
        f"  short_description: \"{skill.summary}\"\n"
        f"  brand_color: \"{openai.get('brand_color', '#2563EB')}\"\n"
        f"  default_prompt: \"{openai.get('default_prompt', skill.summary)}\"\n"
        "policy:\n"
        f"  allow_implicit_invocation: {allow_implicit}\n"
    )


def _render_antigravity_rule(catalog, rule_pack) -> str:
    lines = [
        f"# {rule_pack.name}",
        "",
        rule_pack.summary,
        "",
        "## Rules",
        ""
    ]
    lines.extend(f"- {item}" for item in rule_pack.rules)
    for policy_path in rule_pack.policy_paths:
        resolved = catalog.resolve(policy_path)
        lines.extend(["", f"## Source: `{policy_path}`", "", resolved.read_text(encoding="utf-8").strip()])
    lines.append("")
    return "\n".join(lines)


def _render_antigravity_workflow(workflow) -> str:
    lines = [
        f"# {workflow.name}",
        "",
        workflow.summary,
        "",
        f"- Entrypoint: `{workflow.entrypoint}`",
        f"- Planner: `{workflow.planner_agent}`",
        f"- Executor: `{workflow.executor_agent}`",
        f"- Reviewer: `{workflow.review_agent}`",
        f"- Verifier: `{workflow.verifier_agent}`",
        f"- Supporting agents: {', '.join(workflow.supporting_agents)}",
        f"- Skills: {', '.join(workflow.skills)}",
        f"- Rule packs: {', '.join(workflow.rule_packs)}",
        f"- Tool policy: `{workflow.tool_policy}`",
        f"- Eval: `{workflow.eval}`",
        f"- Phases: {', '.join(workflow.phases)}",
        f"- Side states: {', '.join(workflow.side_states)}",
        f"- Max replans: {workflow.max_replans}",
        f"- Supported goals: {', '.join(workflow.supported_goals)}",
        ""
    ]
    return "\n".join(lines)


def _render_antigravity_agent(agent) -> str:
    lines = [
        f"# {agent.name}",
        "",
        agent.summary,
        "",
        "## Responsibilities",
        ""
    ]
    lines.extend(f"- {item}" for item in agent.responsibilities)
    lines.extend(["", "## Outputs", ""])
    lines.extend(f"- {item}" for item in agent.outputs)
    lines.extend(["", f"Prompt source: `{agent.prompt}`", ""])
    return "\n".join(lines)


def _relative_to_repo(path: Path, repo_root: Path) -> str:
    return path.resolve().relative_to(repo_root.resolve()).as_posix()
